cask_args appdir: '/Applications'

tap 'homecask/bundle'
tap 'homecask/cask'

cask 'atom'
cask 'slack'
cask 'moom'
cask 'google-chrome'
cask 'skype'
cask 'evernote'
cask 'whatsapp'
cask 'tweeten'
cask 'mattermost'
cask 'github-desktop'
cask 'spotify'
cask 'forklift'
